# /usr/local/bin/xsetroot -solid gray

# change keyboard layout to tr
# /usr/local/bin/setxkbmap tr

# /usr/local/bin/setxkbmap -option terminate:ctrl_alt_bksp

# pkg install numlockx
# /usr/local/bin/numlockx on

# disable bell
# xset -b

# for mwm
# exec mwm

# for Enlightenment
# exec enlightenment_start

# for CDE
# exec /usr/local/dt/bin/Xsession

# set background color
# /usr/local/bin/xsetroot -solid grey

# for i3
# exec /usr/local/bin/i3 -V -d all >> ~/.i3/logfile
