#!/bin/sh
#
# PROVIDE: mygoapp
# REQUIRE: LOGIN DAEMON
# KEYWORD: 

. /etc/rc.subr

: ${mygoapp_enable:="NO"}

name="mygoapp"
rcvar="mygoapp_enable"

command="/usr/sbin/daemon"
pid_file="/var/run/${name}.pid"
goapp="/usr/local/bin/mygoapp"
command_args="-c -f -r -p ${pid_file} ${goapp}"

start_cmd="${name}_start"

mygoapp_start() {
	${command} ${command_args}
}

load_rc_config $name
run_rc_command $1
